version: '3.8'

services:
  db:
    container_name: mysql_container
    image: mysql:latest
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD = ROOT_PASSWORD
      - MYSQL_DATABASE = DB_NAME
      - MYSQL_USER = DB_USER
      - MYSQL_PASSWORD = DB_PASSWORD
    ports:
      - "3308:3306"
    volumes:
      - ./mysql_data:/var/lib/mysql

  phpmyadmin:
    container_name: phpmyadmin_container
    image: phpmyadmin/phpmyadmin
    restart: always
    environment:
      - MYSQL_HOST = localhost
      - MYSQL_USER = root
      - MYSQL_PASS = password
      - MYSQL_DB = marketVerse
    ports:
      - "8080:80"
    depends_on:
      - db
    volumes:
      - ./phpmyadmin_sessions:/sessions

  api:
    container_name: ecommerce_api
    restart: always
    image: ecommerce_api-prod
    build: 
      context: ./backend-server
      dockerfile: Dockerfile
    env_file:
      - ./backend-server/.env
    ports:
      - "4000:4000"
    depends_on:
      - db
    develop:
      watch:
        - action: sync
          path: ./backend-server
          target: /usr/src/api
          ignore:
            - node_modules/
        - action: rebuild
          path: ./backend-server/package.json
    
  client:
    container_name: ecommerce_client
    restart: always
    image: ecommerce-client-prod
    build:
      context: ./frontend-server
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - api
    develop:
      watch:
        - action: sync
          path: ./frontend-server
          target: /usr/src/client
          ignore:
            - node_modules/
        - action: rebuild
          path: ./frontend-server/package.json